// file_check.proto
// protoc --proto_path=proto --go_out=pb --go_opt=paths=source_relative \
//   --go-grpc_out=pb --go-grpc_opt=paths=source_relative proto/*.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: file_check.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileWalk_GetFiles_FullMethodName     = "/pb.FileWalk/GetFiles"
	FileWalk_CheckFileMD5_FullMethodName = "/pb.FileWalk/CheckFileMD5"
)

// FileWalkClient is the client API for FileWalk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileWalkClient interface {
	GetFiles(ctx context.Context, in *Path, opts ...grpc.CallOption) (*FileList, error)
	CheckFileMD5(ctx context.Context, in *FileCheckRequest, opts ...grpc.CallOption) (*FileCheckResponse, error)
}

type fileWalkClient struct {
	cc grpc.ClientConnInterface
}

func NewFileWalkClient(cc grpc.ClientConnInterface) FileWalkClient {
	return &fileWalkClient{cc}
}

func (c *fileWalkClient) GetFiles(ctx context.Context, in *Path, opts ...grpc.CallOption) (*FileList, error) {
	out := new(FileList)
	err := c.cc.Invoke(ctx, FileWalk_GetFiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileWalkClient) CheckFileMD5(ctx context.Context, in *FileCheckRequest, opts ...grpc.CallOption) (*FileCheckResponse, error) {
	out := new(FileCheckResponse)
	err := c.cc.Invoke(ctx, FileWalk_CheckFileMD5_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileWalkServer is the server API for FileWalk service.
// All implementations must embed UnimplementedFileWalkServer
// for forward compatibility
type FileWalkServer interface {
	GetFiles(context.Context, *Path) (*FileList, error)
	CheckFileMD5(context.Context, *FileCheckRequest) (*FileCheckResponse, error)
	mustEmbedUnimplementedFileWalkServer()
}

// UnimplementedFileWalkServer must be embedded to have forward compatible implementations.
type UnimplementedFileWalkServer struct {
}

func (UnimplementedFileWalkServer) GetFiles(context.Context, *Path) (*FileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiles not implemented")
}
func (UnimplementedFileWalkServer) CheckFileMD5(context.Context, *FileCheckRequest) (*FileCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFileMD5 not implemented")
}
func (UnimplementedFileWalkServer) mustEmbedUnimplementedFileWalkServer() {}

// UnsafeFileWalkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileWalkServer will
// result in compilation errors.
type UnsafeFileWalkServer interface {
	mustEmbedUnimplementedFileWalkServer()
}

func RegisterFileWalkServer(s grpc.ServiceRegistrar, srv FileWalkServer) {
	s.RegisterService(&FileWalk_ServiceDesc, srv)
}

func _FileWalk_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Path)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileWalkServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileWalk_GetFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileWalkServer).GetFiles(ctx, req.(*Path))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileWalk_CheckFileMD5_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileWalkServer).CheckFileMD5(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileWalk_CheckFileMD5_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileWalkServer).CheckFileMD5(ctx, req.(*FileCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileWalk_ServiceDesc is the grpc.ServiceDesc for FileWalk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileWalk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FileWalk",
	HandlerType: (*FileWalkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFiles",
			Handler:    _FileWalk_GetFiles_Handler,
		},
		{
			MethodName: "CheckFileMD5",
			Handler:    _FileWalk_CheckFileMD5_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_check.proto",
}
